### ISSUE TITLE
InitialFilterValue like InitialSort

### ISSUE THREAD

**Issue by DanielStaroscik** [NonFactors/AspNetCore.Grid#236]
Hi, i've another question it will bavailable to create `InitialFilterValue()` to set initial filter value?
It can be used like `InitialSort()` method.

**Comment by Muchiachio** [comment]
There is no built in way to do that, but it's possible to forcefully set filter values, resulting in initial filter.
It's not added in the grid itself, because with initial filter there is no real way for the user to go back to the "no filter mode" without adding some kind of unique url markers, which is not ideal.
