### ISSUE TITLE
upgrade to version 5.1.2 broke paging

### ISSUE THREAD

**Issue by RichJohnsone** [NonFactors/AspNetCore.Grid#247]
Hi, I have recently tried upgrading from 4.0.3 to 5.1.2 and now the paging controls only show 1 page where there should be over 100. I have followed the installation instructions and upgraded all the shared views, css and js files.

**Comment by Muchiachio** [comment]
Can you share a repro? Paging seems to be working on [example page](https://mvc6-grid.azurewebsites.net/Grid/Paging) using `v5.1.2` sources.

**Comment by RichJohnsone** [comment]
sadly doing that will be a difficult and time-consuming process, as the grids are part of a large private website. If it helps I have examined the pager object in the view creating it at run-time and all the necessary variables are populated correctly - rowsperpage = 10, total rows = 1027, currentpage = 1. Attached is an image of the paging section that gets produced.
![Capture](https://user-images.githubusercontent.com/22589975/73548791-47675380-4439-11ea-9df8-0df2aadaa000.PNG)

**Comment by RichJohnsone** [comment]
I have also noticed that GridProcessorType.Manual is no longer available - only either Pre or Post. Is this an intended change as of version 5.1.2? In any case I have tried it with both Pre and Post and they both produce the same result as above.

**Comment by Muchiachio** [comment]
You don't have to copy paste your project, just new project -> add grid -> see it not working.
I can't really help if it works in all our code bases and the example page, as it's most likely caused by your code base and not some bug in the grid I can observe and fix :(

`GridProcessingType.Manual` got moved up the hierarchy from the pager to the grid itself, to avoid people thinking that filtering/sorting would continue to work with hand written queries.

You can see the usage example [here](https://mvc6-grid.azurewebsites.net/Grid/ManualProcessing).

**Comment by RichJohnsone** [comment]
Thank you so much, for the grid and snappy responses. Moving GridProcessingType.Manual up as per your example fixed it.
